backend:
  name: github
  repo: ericthelemur/uwcs-site
  base_url: https://127.0.0.1:5000
  cms_label_prefix: "[CMS] "
media_folder: "static/images"
public_folder: "/images"
site_url: https://github.com/ericthelemur/uwcs-site
logo_url: https://ericthelemur.github.io/uwcs-site/assets/logo_compact.svg

collections:
  - name: "news" # Used in routes, e.g., /admin/collections/blog
    label: "News" # Used in the UI
    folder: "content/news" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Template", name: "template", widget: "hidden", default: "specific/news.html"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "News Date", name: "date", widget: "datetime"}
      - {label: "Categories", name: "taxonomies.categories", widget: "select", options: ["Newsletter", "Test"]}
      - {label: "Term", name: "taxonomies.terms", widget: "string", pattern: ["[0-9]{2}/[0-9]{2}( T[0-4])?", "Format as '22/23 T2', term is optional"]}
      - {label: "Body", name: "body", widget: "markdown"}